### PR TITLE
Fixing Owncloud Profile

### PR DESCRIPTION
**Pull request by dasrecht**
I did some work here to swap out the owncloud package installation with the git checkout.

### CODE REVIEW

**Comment by dasrecht** [comment]
Yes and feel free to squash the whole stuff on merge :)

**Comment by dasrecht** [comment]
Don't merge that one in yet. i made some changes yesterday and moved it from uwsgi to the fpm profile. after some testing i'll come up with the commits.

**Comment by dasrecht** [comment]
Huston, wer'e good to go ;)

**Comment by tobru** [comment]
@dasrecht should I merge this one? =)

**Comment by dasrecht** [comment]
no ;) (for your own sake)

On 7 June 2016 11:41:38 CEST, Tobias Brunner notifications@github.com wrote:

> @dasrecht should I merge this one? =)
> 
> ---
> 
> You are receiving this because you were mentioned.
> Reply to this email directly or view it on GitHub:
> https://github.com/vshn/uhosting/pull/27#issuecomment-224230785

## 

Sent while on the road. Therefore straight to the point.

**Comment by tobru** [comment]
@dasrecht Your contribution to uhosting was much appreciated back then. Times have changed, uhosting is history and this project archived. Kthxbye :smile_cat:

**Pull request closed without merging**
